### PR TITLE
admin can now toggle approved status

### PR DESCRIPTION
**Pull request by Peter-Springer**
toggleapproved
Admin can undo an approval

### CODE REVIEW

**Comment by kerrd89** [comment]
i pushed to this branch making a small change to toggle the text on the button, so it says pending if the spike is already approved.

**Comment by Jeff-Duke** [comment]
As of now the location is staying assigned to the spike when we put it back to a pending status.  We should set it up to remove the location and update firebase when we put it back to a pending status.

**Comment by Peter-Springer** [comment]
clear-location

when spike is unapproved location is reset

**Comment by Jeff-Duke** [comment]
This looks great!  I love having the buttons disabled and having it only enable once a room is picked.

**Pull request merged**
