### PR TITLE
test Spike component

### PR DESCRIPTION
**Pull request by swanie21**
# Purpose 
Test Spike, Spikes, and Header components 

# Status
Spike component testing is complete 
Issues with testing Spikes and Header components 

With the Header component I tried to mock myself as a user, but the user is still undefined when I run the test suite 
screen shot 2017-01-07 at 2 49 49 pm

With the Spikes component I can make some tests pass by commenting lines out in the component file itself, but obviously we need this code. Not sure why the tests won't pass otherwise. 
screen shot 2017-01-07 at 2 46 59 pm

Currently those test files are commented out, so if you would like to see the error messages you will need to comment them back in

### CODE REVIEW

**Comment by kccrs** [comment]
Kirsten I am having those same issues with dateOptions while trying to test the Admin pages.  Maybe we can collaborate tomorrow unless someone else knows why this is a problem.

**Comment by swanie21** [comment]
Let me know if you make headway with the mock user, otherwise let's pair tomorrow. Yes, such a strange error with the dateOptions not being a function.

**Comment by kccrs** [comment]
I did it!  I probably changed too many things for one commit and one PR, but hey... they were similar issues.  

For the Header component -  I passed the user into the component instead of defining user inside the test function.

For Spikes component - I moved the dateOptions function out of App and into Spikes as it wasn't being passed properly.   When it was passed into Spikes it had no arguments, even though it should have "spikes" as arg, but if you tried to pass "spikes" through it blew up as well.  The exact same issue appeared in the AdminSpikes component, so I am duplicating this for that testing on another branch.  I also created a mockSpikes file so that we can pass those in to Spikes and AdminSpikes and do some deeper testing with the mock data.

**Comment by swanie21** [comment]
After Casey helped mock the user in the header and created mockSpikes I was able to finish testing the Spikes and Header components. Additionally, the removal of the dateOptions function to the Spikes components allowed for the testing to be completed. Nice work Casey!

We have 35 tests currently.

**Pull request merged**
