### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by swanie21**
## Purpose
Add styling - matched the styling on Turing's website to maintain Turing's brand 

## Approach
* Added new classNames to elements in order to style them - made sure that the className syntax was consistent by naming elements with camelcase with the first word capitalized
* Added Turing logo favicon
* Created stylesheets for each component 
* Created Spike content cards in order for responsive design
* Added media queries for responsive design on mobile and ipad
* Included background collage image on login page - considering video as background
* Brought in user profile image to be part of the login information 

## Pre-merge questions and TODOs
None, this PR is complete with responsive design and is ready to merge pending code review. Open to suggestions and we can change any styling after review. After merge, run `npm i` since a `url-loader` dependency was needed in order to make the background image work.

### CODE REVIEW

**Comment by Peter-Springer** [comment]
@Jeff-Duke why the in progress label?

**Comment by Peter-Springer** [comment]
@swanie21 I think that looks great so far. Only thing I noticed was that the elements in the header start to get crowded in the ipad view. Not sure if we really care just an observation.

**Comment by Peter-Springer** [comment]
screen shot 2017-01-02 at 12 04 46 pm

**Comment by swanie21** [comment]
I remember seeing the email crammed like that, but wasn't sure whether to drop the login info down like in mobile or not. Another solution would be to take out "Logged in as." Do we really need that?

**Comment by swanie21** [comment]
screen shot 2017-01-02 at 12 13 20 pm

**Comment by Peter-Springer** [comment]
Looks good to me. What do you think about moving the sign out bottom to the top right?

**Comment by swanie21** [comment]
screen shot 2017-01-02 at 12 18 14 pm

Like this?

**Comment by Peter-Springer** [comment]
Yeah looks good. What should we change the "vote" button to? That was just a place holder maybe sign up? Needs something more aligned with what you are doing.

**Comment by swanie21** [comment]
Maybe "select"

**Comment by swanie21** [comment]
@Peter-Springer The Sign Out button placement has moved. The ipad header has been corrected. The "Vote" button has been changed to a "Join" button. Just updated the PR with these changes.

**Comment by Peter-Springer** [comment]
Cool, I noticed you removed the id that was on the form in lib/components/Spike.js. That id was necessary to make the form clear after hitting the submit button. Can you add that back please.

**Comment by swanie21** [comment]
@Peter-Springer Added the id back, good catch! Also I saw when you made two cards the spacing in between is large, so I removed the `justify-content: space-between`

**Comment by Peter-Springer** [comment]
Thanks! Are you working on the admin page also? Just asking to avoid people doing duplicate work. 
screen shot 2017-01-02 at 2 43 21 pm

**Comment by swanie21** [comment]
I haven't touched the admin since I don't think I have access...but I can once I have access. I wonder if this PR should be closed first though because there were so many file changes.

**Comment by Peter-Springer** [comment]
to make yourself an admin just go to the file lib/allAdmins.js and change the email to your own and then you can see the admin page but ok I will close this PR.

**Pull request merged**
