### PR TITLE
Guest speaker

### PR DESCRIPTION
**Pull request by Peter-Springer**
This PR implements basic functionality for an admin to add a guest speaker.

### CODE REVIEW

**Comment by kccrs** [comment]
Looks good.  Would be nice to have an indicator for the admin to see that the speaker was submitted, or have it display the speaker on admin page as well.

**Comment by Peter-Springer** [comment]
fair point I can add that

**Comment by Peter-Springer** [comment]
speaker is render for the admin and user now

**Comment by swanie21** [comment]
That was a good change, so that the admin had some feedback with the submittal of a guest speaker. Definitely needs some styling now!

**Pull request merged**
