### PR TITLE
all axe accessibility tests pass

### LINKED ISSUE #73: Accessibility testing
Use Axe testing or other accessibility tools.

### PR DESCRIPTION
**Pull request by swanie21**
# Purpose 

All accessibility tests through the aXe Chrome extension pass on both the admin and user pages 

Needed to add `label` tags to form elements, add `src` attributes to images, and fix color contrasts
(the teal and white combo on Turing's website didn't pass the color contrast test, so I used the same color to stick with their color theme, but darkened it until it passed with enough contrast)

Hopefully you can see things better! @kerrd89 

screen shot 2017-01-09 at 11 16 54 pm

closes #73

### CODE REVIEW

**Comment by Jeff-Duke** [comment]
We still have 3 violations on the add guest speaker form for missing labels.

**Comment by swanie21** [comment]
Ok strange, I'll check that out and fix it.

**Comment by swanie21** [comment]
@Jeff-Duke That was super strange, when I ran the aXe test it still said everything passed. But you were right about 3 violations since that guest speaker form was missing three labels, good catch! I've added those labels now and everything should pass now. Also I snuck some `blanchedAlmond` in this branch, can you find it!

**Comment by Jeff-Duke** [comment]
This looks good now.  Merging this branch.

**Pull request merged**
